version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  app:
    container_name: monitor
    build:
      context: .
      dockerfile: Dockerfile
    image: monitor:latest
    ports:
      - 8080:8080

volumes:
  prometheus-data:
